version: '3.8'
services:
  linku-website:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app/
    environment:
      - NODE_ENV=development